### ISSUE TITLE
dftd3-version

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#677] opened 2017-04-05 16:00 UTC
GaTech has known that dftd3-version returns wrong energy from one of the C++ functional calls, leading to a failed test, when build _for_ (not necessarily _on_) 5930 processor family. Fundamental cause is a different number of DFT grid points. @lazaroid at [the forum](http://forum.psicode.org/t/different-dft-grid-behaviour-on-different-machines-very-different-dft-enrgies/460/5) has given a good analysis of the problem.

This issue admits that there is a problem.

**Comment by susilehtola** [comment] 2017-04-05 16:17
After reading through the lengthy exchange on the forum, the problem appears to be that the code that rotates the DFT grid into the standard orientation is not numerically stable. That means the issue is not related just to dftd3, but affects all of psi4.

**Comment by loriab** [comment] 2017-04-05 16:21
Oh, yes, quite agree that it affects DFT in general, and just happens to show up in that test case. Maybe I should have named the issue for the cause, rather than the effect.

**Comment by lazaroid** [comment] 2017-04-05 19:00
Interesting that you mention 5930 processor family. For me, I see the problem on an i7-5960X but not on a Xeon E5520, an i5-2500, nor an i3-3110M.

**Comment by dgasmith** [comment] 2017-04-13 14:43
Closed by #678.

**Closed by dgasmith** 2017-04-13 14:43 UTC
