### ISSUE TITLE
using libERD leads to 2e-int energy = 0

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#173] opened 2015-08-28 10:15 UTC
Psi4 0.3.62 Driver  Git: Rev {master} 1b48d22
compiled with "setup --fc gfortran --erd on"

HF calculation for H2O exists after 2 SCF iterations; no energy change.
output states "Two-Electron Energy =                   0.0000000000000000" 

I specified "INTEGRAL_PACKAGE ERD" in the input.
It is the case for DF and direct SCF. PK gives a non-converging, oscillating SCF. Did not try the other options.

"INTEGRAL_PACKAGE libint" works normally.

Let me know if I should report more data. cheers.

**Comment by jturney** [comment] 2015-08-28 11:40
@keipertk Did you experience anything like this after the libERD patch the other day?

**Comment by keipertk** [comment] 2015-08-28 13:59
I haven't had any issue like that myself

**Comment by jturney** [comment] 2015-08-28 19:45
Looks like I can reproduce the problem. Will take a more detailed look this weekend.

**Comment by loriab** [comment] 2017-01-16 06:02
Just tried a water with direct scf in ERD, and it worked fine, including 2e- energy. This was a while ago in terms of how ERD integrates. And when ERD is expected to work (essentially scf_type=direct only) is now documented. So closing. Please reopen if reappears.

**Closed by loriab** 2017-01-16 06:02 UTC
