### ISSUE TITLE
Different Results on Different Machines

### ISSUE THREAD

**Issue by bwb314** [psi4/psi4#779] opened 2017-08-14 21:38 UTC
A challenging DFT single-point converges to `-2400.0592973332418296 a.u.` using a conda binary (version 1.2a1.dev458 with Python 3.5) with default thresholds on a Mac Pro. However, when I attempt to reproduce the computation (exact same input) on a Ubuntu machine using the same versions of the binary and Python, I get `-2400.0575893688073847 a.u.`, which differs by 1.7 miliHartree.

**Comment by dgasmith** [comment] 2018-04-13 05:35
Pretty sure this is a duplicate of the previous issue. Try `set sad_frac_occ true`.

**Closed by dgasmith** 2018-04-13 05:35 UTC
