### ISSUE TITLE
Psi4 changes directory then PCM is used

### ISSUE THREAD

**Issue by j3mdamas** [psi4/psi4#817] opened 2017-10-08 22:34 UTC
Hi guys,

@raimis found this bug and we are adapting to it on our code, but I find it kind of an ugly workaround. Have you experienced it?

@raimis, can you provide some more details? Thanks!

João

**Comment by loriab** [comment] 2017-10-08 22:39
Yes, if you supply an input and output descriptions, perhaps @robertodr can examine?

**Comment by robertodr** [comment] 2017-10-08 22:40
@j3mdamas @loriab sure thing. Just send an example :wink:

**Comment by dgasmith** [comment] 2017-10-09 00:09
The issue is in the python helper. We don’t save the current working directory before hoping around in the filesystem. Could be good to do a general pass to make sure we only temporarily mess with the CWD. 

-Daniel Smith

**Comment by j3mdamas** [comment] 2017-10-09 16:03
@raimis, could you post here an example? if @dgasmith already spot it, maybe it's easier to track it down?
Thanks guys!

**Comment by dgasmith** [comment] 2017-10-09 16:08
Pretty sure the issue is with this [function](https://github.com/psi4/psi4/blob/eec3fd68d69b912a82274c916c3b0b30438302ba/psi4/driver/p4util/python_helpers.py#L230). It just needs something to save the CWD and switch back when its done.

**Comment by j3mdamas** [comment] 2017-12-13 12:46
@dgasmith was this dropped? or just less priority?

**Comment by dgasmith** [comment] 2017-12-13 13:15
@robertodr Made a PR a bit ago, any updates there?

**Comment by robertodr** [comment] 2017-12-13 16:47
The PR is #818 and I was waiting for a minimal failing example to test that that was actually the fix needed.

**Comment by raimis** [comment] 2017-12-14 15:14
@dgasmith @robertodr 

A simple example:

Without PCM, the working directory does not change:
```python
import os

geometry('H -.5 0 0\nH .5 0 0\nsymmetry c1')

#pcm = { 
#    Medium { Solvent = Water }
#    Cavity { Type = GePol }
#}

energy('HF/3-21G')

print(os.getcwd())
```
```bash
$ psi4 test.py 
/home/raimis/debug/psi4_PCM
```

With PCM, the working directory changes:
```python
import os

geometry('H -.5 0 0\nH .5 0 0\nsymmetry c1')

pcm = { 
    Medium { Solvent = Water }
    Cavity { Type = GePol }
}

energy('HF/3-21G')

print(os.getcwd())
```
```bash
$ psi4 test.py 
/tmp/psi.12147.pcmsolver.604855c3
```

A small detail, but it messes up our pipeline.

**Comment by j3mdamas** [comment] 2018-01-10 19:10
PR https://github.com/psi4/psi4/pull/818 was merged. Should we close this? @loriab made some extra comments on the PR, so I don't know

**Comment by loriab** [comment] 2018-01-10 19:40
Broadly, [psithon](http://psicode.org/psi4manual/master/tutorial.html) is when you make a molecule with `molecule name {...}`, use other non-strictly-python syntax in your input and submit the file to the executable `bin/psi4`, while [psiapi](http://psicode.org/psi4manual/master/psiapi.html) is when you `import psi4`, make a molecule with `name = psi4.geometry(...)`, use strictly python syntax, and submit the file to python interpreter. Sounds like you use psithon (only choice until Oct 2016 (dev) or May 2017 (release)), though you might like psiapi.

Have you tested the fix with #818? My concern, once I looked carefully (albeit late at night, so I could be talked down), was that to handle pcm there's a snippet of code in the inputparser (only psithon passes through the input parser) that 818 _didn't_ change and a very similar snippet (that only psiapi uses) that 818 _did_ change. So I worry that 818 _didn't_ fix your problem and _did_ break pcm in psiapi mode for me (shows up in `psi4 --test` that's actually running psiapi).

If 818 fixes your problem, then I'm imagining things. Could you read this over, @robertodr, and see if it raises your alarm? pcm in `psi4 --test` is broken for me, and this was my theory why.

**Comment by robertodr** [comment] 2018-01-10 21:52
Apologies for slowness! I _did_ test both Psithon _and_ PsiAPI before submitting the PR, so I am a bit surprised things are broken for you @loriab I can surely take another look. The long term solution is to ditch the additional input file for PCM. This requires changes in the PCM library that I am (alas, slowly) making right now.

**Comment by loriab** [comment] 2018-01-10 23:24
@j3mdamas, just an update, don't close this issue. The saga of input parsing for a 2-language program that works with several QC programs ranging from monolithic to flexible (users can actually access the stage between the language handover in psi) that pcmsolver contends with continues.

**Comment by j3mdamas** [comment] 2018-01-11 00:41
I won't close then. @raimis could you test PR #818?

Yeah, we use psithon. Could be interesting to change to psiapi, but we're happy with the passing the input to bin/psi4.

**Comment by loriab** [comment] 2018-01-11 01:04
Actually not worth testing 818. It won't have had any effect on psithon.

**Comment by loriab** [comment] 2018-01-11 01:09
Just noticed [this](https://github.com/raimis/htmd/blob/a43918d2642585e61882f1f22d4502809611374c/htmd/qm/psi4.py#L226). I don't recall if it's merged to master yet, but I changed it and others https://github.com/psi4/psi4/blob/scfitertopy/psi4/src/psi4/libmints/oeprop.cc#L1355 . You may prefer to grab stuff from psi variables `psi4.print_variables()` if you've only the output file to work from.

**Comment by j3mdamas** [comment] 2018-01-11 01:13
@loriab thanks for the input! I think there is/was a more fundamental reason for us to be using the bin/psi4 and I/O processing, but I'll discuss with @raimis tomorrow.

**Comment by loriab** [comment] 2018-01-11 16:55
Back to the examples from https://github.com/psi4/psi4/issues/817#issuecomment-351739145, @robertodr has a scheme that won't get the dir right from within the psi input file, but it will fix the dir upon completion of psi4 execution, as shown below. Would that fix your pipeline for now?

```
>>> cat test.py
import os

geometry('H -.5 0 0\nH .5 0 0\nsymmetry c1')

pcm = { 
    Medium { Solvent = Water }
    Cavity { Type = GePol }
}

energy('HF/3-21G')

print(os.getcwd())

>>> psi4 test.py 
/tmp/psi.12147.pcmsolver.604855c3
>>> pwd
/home/raimis/debug/psi4_PCM
```

**Comment by j3mdamas** [comment] 2018-01-11 21:47
I think so, as we only care about the CWD after the full execution and not inside the script. Right @raimis?

**Comment by raimis** [comment] 2018-01-12 10:56
Hi @loriab and @robertodr,

Thanks for your effort!

Regarding `Psithon` and `PsiAPI`, we are using both.  For older products (e.g. https://github.com/Acellera/htmd/blob/master/htmd/qm/psi4.py), it is still `Psithon`, but will change to `PsiAPI` eventually. For new development, we (at least me) are already using `PsiAPI.` So ideal, the both should work consistently.

Regarding a simple specific usage from https://github.com/Acellera/htmd/blob/master/htmd/qm/psi4.py, we have two scripts:
```bash
$ cat run.sh
#!/bin/sh

export HTMD_PSI4_WORKDIR=$(pwd)
psi4 -i psi4.in -o psi4.out &> psi4.log
```
```python
$ cat psi4.in
set_num_threads( 8 )
memory 2.000000 gb

set { reference rks }
set { basis cc-pVDZ }

molecule MOL {
    0 1
    noreorient
    nocom
    symmetry c1
    O    1.014300  -0.002300   0.060500
    O    2.462400  -0.107500  -0.002400
    H    0.821200  -0.823600  -0.430600
    H    2.655500   0.713700   0.488700
}

pcm = { 
    Medium { Solvent = Water }
    Cavity { Type = GePol }
}

set optking { dynamic_level = 1 }

energy, wfn = optimize('B3LYP-D3', return_wfn=True)

import os
os.chdir(os.environ['HTMD_PSI4_WORKDIR'])

oeprop(wfn, 'DIPOLE', 'QUADRUPOLE', 'MULLIKEN_CHARGES')

with open('psi4out.xyz', 'w') as f:
    f.write('4 ' )
    f.write('%.12f\n' % energy)
    f.write(MOL.save_string_xyz())
```
We need that the working directory to be not changed after `optimize` (and `energy`) returns as we do some analysis and write a few files in general (in this case just `psi4out.xyz`). So, we have an ugly hack to fix it.

**Comment by dgasmith** [comment] 2018-03-04 17:17
Hmm, I think should all be fixed now or am I mistaken?

**Comment by loriab** [comment] 2018-03-04 17:20
Yes. Though as I've fallen down on my conda-building duties, haven't personally confirmed. Should be safe to close.

**Comment by j3mdamas** [comment] 2018-03-04 23:24
thanks! from which psi4 version will this change start?

**Comment by loriab** [comment] 2018-03-04 23:26
It's been in since late January. But the nightly conda build machinery is broken until I get some time to universally update to the new conda-build compilers (prototyped in the fall that they do work with psi) which won't be until after ACS. As far as stable release, the fix'll be in the next one, 1.2.

**Comment by j3mdamas** [comment] 2018-03-04 23:27
1.2, thanks!

**Comment by loriab** [comment] 2018-04-13 06:40
This was fixed. If not, it can reopen.

**Closed by loriab** 2018-04-13 06:40 UTC
