### ISSUE TITLE
SCF Count Failure

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2594] opened 2022-06-04 20:08 UTC
When I run the following input file on [master](https://github.com/psi4/psi4/commit/9240cbeb9343f76b39e3ec34daa844ed04cd8b66):

```
memory 2 gb

molecule mol {
-1 2
C 0.00000000 0.00000000 0.00000000
C 1.21064700 0.71690500 0.00000000
C 1.20587000 2.10633100 0.00000000
C 0.00000000 2.80649500 0.00000000
C -1.20587000 2.10633100 0.00000000
C -1.21064700 0.71690500 0.00000000
H -2.14648500 0.17133400 0.00000000
H -2.14658900 2.64534700 0.00000000
H 0.00000000 3.89046700 0.00000000
H 2.14658900 2.64534700 0.00000000
H 2.14648500 0.17133400 0.00000000
C 0.00000000 -1.42321300 0.00000000
C 0.00000000 -2.63387100 0.00000000
C 0.00000000 -4.05708400 0.00000000
C -1.21064700 -4.77398900 0.00000000
C -1.20587000 -6.16341500 0.00000000
C 0.00000000 -6.86357900 0.00000000
C 1.20587000 -6.16341500 0.00000000
C 1.21064700 -4.77398900 0.00000000
H 2.14648500 -4.22841800 0.00000000
H 2.14658900 -6.70243100 0.00000000
H 0.00000000 -7.94755100 0.00000000
H -2.14658900 -6.70243100 0.00000000
H -2.14648500 -4.22841800 0.00000000

}

set scf_type df
set basis aug-cc-pVTZ
set reference uks

mol.update_geometry()
mol.symmetrize(1e-3)

energy('b3lyp')
```

I observe
```
  ==> Pre-Iterations <==

  SCF Guess: Superposition of Atomic Densities via on-the-fly atomic UHF (no occupation information).

   -------------------------
    Irrep   Nso     Nmo    
   -------------------------
     Ag       160     160 
     B1g      130     130 
     B2g       63      63 
     B3g       84      84 
     Au        63      63 
     B1u       84      84 
     B2u      160     160 
     B3u      130     130 
   -------------------------
    Total     874     874
   -------------------------

  ==> Iterations <==

                           Total Energy        Delta E     RMS |[F,P]|

   @DF-UKS iter SAD:  -538.61970612101391   -5.38620e+02   0.00000e+00 

Traceback (most recent call last):
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/bin//psi4", line 338, in <module>
    exec(content)
  File "<string>", line 53, in <module>
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 86, in scf_compute_energy
    self.iterations()
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 429, in scf_iterate
    self.form_C()

RuntimeError: 
Fatal Error: Count 49 alpha electrons, expected 48.
This is a bug. Please file a report.
Error occurred in file: /Users/jonathonmisiewicz/psi4/psi4/src/psi4/libscf_solver/hf.cc on line: 482
```

Quick counting says that 48 is the expected number of alpha electrons for this system.

**Comment by JonathonMisiewicz** [comment] 2022-06-04 20:10
Also, this is carried forward from [forums](http://forum.psicode.org/t/radical-anion-error-bug-in-1-6/2505/3).

**Comment by susilehtola** [comment] 2022-06-06 16:41
I bet this is also one of those edge cases I've described previously. The problem is that instead of storing the occupations separately for alpha and beta, Psi4 tries to mimic the restricted open shell method and write everything in terms of doubly occupied and singly occupied orbitals.

The problem is that if you have a beta orbital occupied in a symmetry block, then the code ends up flipping its spin to an alpha electron, since the number of doubly and singly occupied electrons are defined as `min(nalpha, nbeta)` and `abs(nalpha-nbeta)`, respectively.

**Comment by susilehtola** [comment] 2022-06-06 16:41
That is, this is probably a duplicate of https://github.com/psi4/psi4/issues/2476

**Comment by susilehtola** [comment] 2022-06-06 16:45
The bug is also basis set dependent (def2-SVPD runs fine in Psi4 1.3.2), which also points to this.

As a workaround, this issue can probably be solved for this system by using a better initial guess.

**Comment by JonathonMisiewicz** [comment] 2022-06-07 13:53
Thanks for the analysis.

I'm _extremely_ unhappy about this, but alas, don't have the time to deal with it at the moment.

**Comment by sbembenek18** [comment] 2022-06-07 19:39
@susilehtola 
If by 'using a better initial guess', you mean slowing working up to the desired level of theory, then yes, it seems to help, but I am only able to get it to DFT; B3LYP-D3BJ; 6-311++G**, but not to the desired basis of aug-cc-pVTZ. 

If you have additional thoughts on a workaround, please let me know. 

thanks!

**Comment by sbembenek18** [comment] 2022-06-08 01:18
@susilehtola
I was able to run this calculation under 1.3.2 to completion (and in 1.4.1 for almost 2 iterations -- past the problem point in 1.6 -- before stopping it myself. Working on 1.5 -- having issues with running it). So it does not seems like it's the physics of the ground state --???

OK, point taken on not using the Dunning sets with DFT. Is your concern here primarily the inefficiency of the SCF calculations when doing so, rather than loss of quality? Thanks for the suggestions, I will try these other sets. 

When you say 'initial guess' -- other than starting with a different set of coordinates, or working through different levels of theory as described previously, I'm unclear of other approaches for this -- please advise.

thanks again.

**Comment by susilehtola** [comment] 2022-06-08 13:38
@sbembenek18 level of theory = functional+basis set

The Dunning sets are inefficient for HF and DFT since they're aimed for post-HF correlation. You can get away with a smaller basis set / get a more converged result by using a basis set tailored for HF/DFT.

To get the calculation to converge you can try out
- doing a preliminary calculation in a smaller basis (`basis_guess` option in Psi4; this is often adviseable in large basis sets like aug-cc-pVTZ since it saves CPU time)
- switching to another initial guess, e.g. sap or huckel, since the problem is that the SAD guess orbital occupation can't be satisfied with Psi4 at the moment

**Comment by JonathonMisiewicz** [comment] 2022-06-16 18:56
> I bet this is also one of those edge cases I've described previously. The problem is that instead of storing the occupations separately for alpha and beta, Psi4 tries to mimic the restricted open shell method and write everything in terms of doubly occupied and singly occupied orbitals.
> 
> The problem is that if you have a beta orbital occupied in a symmetry block, then the code ends up flipping its spin to an alpha electron, since the number of doubly and singly occupied electrons are defined as `min(nalpha, nbeta)` and `abs(nalpha-nbeta)`, respectively.

Confirmed. `alphapi` is `14  7  1  2  1  2  13  8` where `betapi` is `14  8  1  1  0  2  13  8`. Note the second irrep.

**Comment by JonathonMisiewicz** [comment] 2022-08-12 18:25
While #2619 fixes this as expected, the input file takes ~50 minutes to run on my laptop. Trying to shorten it by reducing the basis set (aTZ -> aDZ) no longer reproduces the `betapi_[h] > nalphapi_[h]` behavior.

**Closed** 2022-08-12 19:29 UTC
Labels: scf, crash, debugging-needed
