### ISSUE TITLE
CMake sets Boost Include path and Boost Library paths to different boost versions. 

### ISSUE THREAD

**Issue by amjames** [psi4/psi4#313] opened 2016-03-14 20:04 UTC
## Information:
I have two versions of boost installed on my system. 

- I installed boost 1.59 in a conda env using the ([recipe](https://github.com/conda/conda-recipes/tree/b9570c14d5a25ac88b98c6c597365bfcba4174ce/boost)) from the condo/conda-recipies repo ( before the boost recipe was upgraded to 1.60.0). Installed in `$HOME/anaconda/envs/psi4-py2.7`  

- Hombrew boost 1.60.0 installed in `/usr/local/Cellar` and linked by hombrew to `/usr/local`

- I am using CMake 3.2.2

## Problem:
1. If I pass the setup args `--boost-libdir/incdir` or the CMake flags `DBOOST_INCLUDEDIR/LIBRARYDIR`  
CMake will report boost version 1.59.0, but actually only set the `INCLUDE` paths correctly, and the `LIBRARY` paths all point to the binaries for 1.60.0 leading to errors in the linking step. 

2. If I `brew unlink boost` then FindBoost.cmake seems to find boost 1.59.0 as I intended, but then the `Boost_FOUND` variable is ignored and the pre-packaged boost 1.55 is configured to build anyway. 

## Details/Examples 
If I run this setup command:

```
./setup --prefix=$HOME/psi4-install \
-DBOOST_INCLUDEDIR=$HOME/anaconda/envs/psi4-py2.7/include \ 
-DBOOST_LIBRARYDIR=$HOME/anaconda/envs/psi4-py2.7/lib \
objdir
```
I see boost 1.59.0 is detected
```
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   filesystem
--   python
--   regex
--   serialization
--   system
--   timer
--   chrono
--   thread
-- Looking for MKL_Free_Buffers
```

However the build will fail in the linking step with the same `undefined reference` errors as others have seen when trying to link against boost 1.60.0 #243  , #312 .  Looking in `CMakeCache.txt` I see that the `Boost_INCLUDE_DIR` has been set correctly but the `Boost_LIBRARY_DIR` and all `Boost_XX_LIBRARY_...` paths have been set to the global boost install in `/usr/local` 

```
//Path to a file.
Boost_INCLUDE_DIR:PATH=/Users/admin/anaconda/envs/psi4-py2.7/include

//Boost library directory
Boost_LIBRARY_DIR:PATH=/usr/local/lib

//Boost python library (debug)
Boost_PYTHON_LIBRARY_DEBUG:FILEPATH=/usr/local/lib/libboost_python-mt.a
```

If I unlink the home-brew boost in `/usr/local` and run the same setup the custom boost is configured to build. 

adding the flags `-DBoost_DEBUG=ON -DBoost_DETAILED_FAILURE_MESSAGE=ON`. I can see all of the output related to FindBoost.cmake is identical. CMake is searching the correct path for the boost library files (`$HOME/anaconda/envs/psi4-py2.7/lib`). And does not add `/usr/local/anything` to the search paths. 

Yet, if boost 1.60.0 is linked it reports it found the correct libraries version 1.59.0, and if those links are removed it reports they are not found. In both cases it sets `Boost_FOUND = 1` but with the boost 1.60.0 links removed the pre-packaged boost is configured to build anyway. 

It is also interesting that `_boost_TEST_VERSIONS` includes 1.55.0-1.58.0. (Both 1.59.0 and 1.60.0 aren't included) I am not sure if that is related to this problem though.

FindBoost.cmake debuting output : 

```
-- Found Python: /Users/admin/anaconda/lib/libpython2.7.dylib  
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:515 ] _boost_TEST_VERSIONS = 1.58.0;1.58;1.57.0;1.57;1.56.0;1.56;1.55.0;1.55
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:517 ] Boost_USE_MULTITHREADED = ON
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:519 ] Boost_USE_STATIC_LIBS = ON
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:521 ] Boost_USE_STATIC_RUNTIME = OFF
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:523 ] Boost_ADDITIONAL_VERSIONS = 
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:525 ] Boost_NO_SYSTEM_PATHS = 
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:577 ] Declared as CMake or Environmental Variables:
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:579 ]   BOOST_ROOT = 
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:581 ]   BOOST_INCLUDEDIR = /Users/admin/anaconda/envs/psi4-py2.7/include
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:583 ]   BOOST_LIBRARYDIR = /Users/admin/anaconda/envs/psi4-py2.7/lib
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:585 ] _boost_TEST_VERSIONS = 1.58.0;1.58;1.57.0;1.57;1.56.0;1.56;1.55.0;1.55
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:654 ] Include debugging info:
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:656 ]   _boost_INCLUDE_SEARCH_DIRS = /Users/admin/anaconda/envs/psi4-py2.7/include;PATHS;C:/boost/include;C:/boost;/sw/local/include
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:658 ]   _boost_PATH_SUFFIXES = boost-1_58_0;boost_1_58_0;boost/boost-1_58_0;boost/boost_1_58_0;boost-1_58;boost_1_58;boost/boost-1_58;boost/boost_1_58;boost-1_57_0;boost_1_57_0;boost/boost-1_57_0;boost/boost_1_57_0;boost-1_57;boost_1_57;boost/boost-1_57;boost/boost_1_57;boost-1_56_0;boost_1_56_0;boost/boost-1_56_0;boost/boost_1_56_0;boost-1_56;boost_1_56;boost/boost-1_56;boost/boost_1_56;boost-1_55_0;boost_1_55_0;boost/boost-1_55_0;boost/boost_1_55_0;boost-1_55;boost_1_55;boost/boost-1_55;boost/boost_1_55
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:678 ] location of version.hpp: /Users/admin/anaconda/envs/psi4-py2.7/include/boost/version.hpp
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:702 ] version.hpp reveals boost 1.59.0
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:787 ] guessed _boost_COMPILER = 
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:797 ] _boost_MULTITHREADED = -mt
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:840 ] _boost_RELEASE_ABI_TAG = -
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:842 ] _boost_DEBUG_ABI_TAG = -d
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:890 ] _boost_LIBRARY_SEARCH_DIRS = /Users/admin/anaconda/envs/psi4-py2.7/lib;/Users/admin/anaconda/envs/psi4-py2.7/include/lib;/Users/admin/anaconda/envs/psi4-py2.7/include/../lib;/Users/admin/anaconda/envs/psi4-py2.7/include/stage/lib;PATHS;C:/boost/lib;C:/boost;/sw/local/lib
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1001 ] Searching for FILESYSTEM_LIBRARY_RELEASE: boost_filesystem-mt-1_59;boost_filesystem-mt;boost_filesystem-mt-1_59;boost_filesystem-mt;boost_filesystem
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1037 ] Searching for FILESYSTEM_LIBRARY_DEBUG: boost_filesystem-mt-d-1_59;boost_filesystem-mt-d;boost_filesystem-mt-d-1_59;boost_filesystem-mt-d;boost_filesystem-mt;boost_filesystem
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1001 ] Searching for PYTHON_LIBRARY_RELEASE: boost_python-mt-1_59;boost_python-mt;boost_python-mt-1_59;boost_python-mt;boost_python
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1037 ] Searching for PYTHON_LIBRARY_DEBUG: boost_python-mt-d-1_59;boost_python-mt-d;boost_python-mt-d-1_59;boost_python-mt-d;boost_python-mt;boost_python
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1001 ] Searching for REGEX_LIBRARY_RELEASE: boost_regex-mt-1_59;boost_regex-mt;boost_regex-mt-1_59;boost_regex-mt;boost_regex
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1037 ] Searching for REGEX_LIBRARY_DEBUG: boost_regex-mt-d-1_59;boost_regex-mt-d;boost_regex-mt-d-1_59;boost_regex-mt-d;boost_regex-mt;boost_regex
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1001 ] Searching for SERIALIZATION_LIBRARY_RELEASE: boost_serialization-mt-1_59;boost_serialization-mt;boost_serialization-mt-1_59;boost_serialization-mt;boost_serialization
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1037 ] Searching for SERIALIZATION_LIBRARY_DEBUG: boost_serialization-mt-d-1_59;boost_serialization-mt-d;boost_serialization-mt-d-1_59;boost_serialization-mt-d;boost_serialization-mt;boost_serialization
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1001 ] Searching for SYSTEM_LIBRARY_RELEASE: boost_system-mt-1_59;boost_system-mt;boost_system-mt-1_59;boost_system-mt;boost_system
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1037 ] Searching for SYSTEM_LIBRARY_DEBUG: boost_system-mt-d-1_59;boost_system-mt-d;boost_system-mt-d-1_59;boost_system-mt-d;boost_system-mt;boost_system
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1001 ] Searching for TIMER_LIBRARY_RELEASE: boost_timer-mt-1_59;boost_timer-mt;boost_timer-mt-1_59;boost_timer-mt;boost_timer
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1037 ] Searching for TIMER_LIBRARY_DEBUG: boost_timer-mt-d-1_59;boost_timer-mt-d;boost_timer-mt-d-1_59;boost_timer-mt-d;boost_timer-mt;boost_timer
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1001 ] Searching for CHRONO_LIBRARY_RELEASE: boost_chrono-mt-1_59;boost_chrono-mt;boost_chrono-mt-1_59;boost_chrono-mt;boost_chrono
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1037 ] Searching for CHRONO_LIBRARY_DEBUG: boost_chrono-mt-d-1_59;boost_chrono-mt-d;boost_chrono-mt-d-1_59;boost_chrono-mt-d;boost_chrono-mt;boost_chrono
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1001 ] Searching for THREAD_LIBRARY_RELEASE: boost_thread-mt-1_59;boost_thread-mt;boost_thread-mt-1_59;boost_thread-mt;boost_thread
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1037 ] Searching for THREAD_LIBRARY_DEBUG: boost_thread-mt-d-1_59;boost_thread-mt-d;boost_thread-mt-d-1_59;boost_thread-mt-d;boost_thread-mt;boost_thread
-- [ /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindBoost.cmake:1088 ] Boost_FOUND = 1
```
... after this point if hombrew boost *is unlinked*:
```
-- Could NOT find Boost                                       
Could not find the following static Boost libraries:
        boost_filesystem
        boost_regex
        boost_serialization
        boost_system
        boost_timer
        boost_chrono
        boost_thread
```
... and if hombrew boost *is linked*: 
```
Boost version: 1.59.0                                                
Boost include path: /Users/admin/anaconda/envs/psi4-py2.7/include
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   filesystem
--   python
--   regex
--   serialization
--   system
--   timer
--   chrono
--   thread
```

My main concern is CMake reporting Boost version 1.59.0, but then using library paths that point to a different version.  I don't know if I would have been able to figure out what was going on if I didn't recognize the linker errors as the boost 1.60.0 incompatibility issue. 
(Good thing I have been reading the issues I guess! :tongue: )

But since `Boost_FOUND = 1` is set in both cases, why is the prepackaged boost being built? 

### Temporary workaround
Using ` -DBUILD_CUSTOM_BOOST=ON` will avoid the issue completely and still build successfully.

**Comment by bennybp** [comment] 2016-03-14 20:29
I've seen the initial problem crop up in other projects, and it may be a problem with CMake. See https://github.com/Homebrew/homebrew/issues/10393, and issues linked to it.

**Comment by loriab** [comment] 2016-03-14 21:03
I don't have a solution, but thanks for the nice exposition of the problem.

I'm a little troubled that your "... after this point if hombrew boost is unlinked" output doesn't have python. If any of `filesystem python regex serialization system timer chrono thread` are missing, it'll trigger building the prepackaged. Would you check again that _all_ those are present as `.a` in your anaconda package? I have gotten psi4 to link against pre-built boost conda packages before on Linux, so the problem is definitely not purely that (though it sounds like it could be an affinity to frameworks thing that crops up on Mac). If you don't have all those `.a`s but do have the `.so`s, you could try toggling https://github.com/psi4/psi4/blob/master/cmake/ConfigBoost.cmake#L14 .

If the above comes up clean, would you want to try
`-DBoost_ADDITIONAL_VERSIONS=1.59 -DBOOST_ROOT=$HOME/anaconda/envs/psi4-py2.7` ? There's no particular reason it'd work, but it's covering a couple more bases.

**Comment by amjames** [comment] 2016-03-14 21:50
@loriab ah! I didn't even check for `.a`s vs `.so`s. It looks like the conda recipe passes the shared flag to `b2` so I only had the `.dylib`s for almost all of the libraries.  

I toggled the `Boost_USE_STATIC_LIBS` flag in `ConfigBoost.cmake` and the paths appear to be set correctly to find the `.dylib`s in `$HOME/anaconda/envs/psi4-py2.7`. I am checking to make sure that compiles fine now. ( I have to admit I don't really know what the difference between `.so` and `.dylib` is but CMake seems to think the `.dylib`s are okay. 

I also modified the recipe so I can build the `.a`s as well.  I report back later this evening after I check these options with hombrew boost linked/unlinked to see if having the .`a`s in the search path stops CMake from using the home-brew binaries. 

Thanks for the help.

**Comment by loriab** [comment] 2016-03-14 22:02
Very good, a lead on a solution! Thinking of `.dylib` as just the Mac version of `.so` hasn't failed me yet.

**Comment by amjames** [comment] 2016-03-18 02:11
I can build+link against my local install of boost successfully, using the modified conda recipe to build the static libs, but only if the hombrew boost is unlinked at setup, *and* compile time..  

If the homebrew boost is linked at the time I run the `setup` script I will end up with the same issue where the local (boost 1.59.0) headers are in the boost inc paths, but the homebrew (1.60.0) libraries end up in the boost lib paths. 

If hombrew boost is unlinked at the time I run the `setup` script I will see both the include and library paths are set to the local boost install in the cmake output. However, if homebrew boost is linked when I run `make` I will get an error in the linking step.  I suspect that the directory where hombrew adds the links to boost (`/usr/local/lib`) are passed as a linker argument by cmake, either by default, or because something else is installed there. Thus, if those links are present I will get the characteristic boost 1.60.0 linking errors.

Hombrew installs boost-python as a separate package so to properly remove all of the links `brew unlink boost boost-python` 

Interestingly I have a similar setup on a laptop running ArchLinux 4.4.5 where boost 1.60.0 was installed globally using `pacman` and I used the conda recipie to install boost 1.59.0 in `$CONDA_ENV_PATH`.  If the conda virtual environment is activated and I use the `setup` args to direct cmake to boost 1.59.0 installed there I have no problems. The correct version is always found, even if I try to `make` with the conda virtual environment deactivated the cmake paths still point to the installation I want even though those paths aren't in my environment, and the build is successful. 

I don't know If I would mark this as resolved, but it is at least understood to where it is predictable.  

For anyone who has run into a similar problem:

If you are using a compatible version of boost installed manually on osx and your build fails to link, even if cmake reported the compatible version of boost was detected it may have detected the desired headers, but not the correct binaries. because homebrew has installed boost 1.60.0 in `/usr/local`. Try running `brew unlink boost boost-python` and running setup/make again. 

This may be related to the issue linked by @bennybp. It seems it has something to do with cmake find package on osx.  I haven't seen any problems come up switching between different versions of python though.

**Comment by loriab** [comment] 2016-03-28 22:48
I think you've sorted this out nicely, @amjames, and it's probably more a cmake issue than a Psi4 one. I've added a warning on this to the Wiki at https://github.com/psi4/psi4/wiki/9_Boost#-how-to-force-use-of-pre-built-boost-libraries-on-mac . If that says what you think it needs to, and you're agreeable to it, I'll close this ticket.

**Comment by amjames** [comment] 2016-03-29 14:50
That looks great to me!

**Closed** 2016-03-29 16:16 UTC
