### ISSUE TITLE
forrtl: error (76): Abort trap signal

### ISSUE THREAD

**Issue by ahmedo047** [psi4/psi4#2084] opened 2021-01-15 21:11 UTC
I installed Psi4 1.4a2.dev78 on Ubuntu-20.04.1 using conda installer but it crashes when I use it with [poltype](https://pren.github.io/poltype/README_INSTALL.html) tool. Do you know how I can fix the below error?
**Error:**
```
forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source             
libgdma.so         00007F14B1B2C10F  for__signal_handl     Unknown  Unknown
libpthread-2.27.s  00007F14B7334980  Unknown               Unknown  Unknown
libc-2.27.so       00007F14B6F6FFB7  gsignal               Unknown  Unknown
libc-2.27.so       00007F14B6F71921  abort                 Unknown  Unknown
core.cpython-37m-  00007F14B40E13D7  Unknown               Unknown  Unknown
core.cpython-37m-  00007F14B26DC86D  Unknown               Unknown  Unknown
core.cpython-37m-  00007F14B26F56B1  Unknown               Unknown  Unknown
core.cpython-37m-  00007F14B271593A  Unknown               Unknown  Unknown
python3.7          000055CE517D7914  _PyMethodDef_RawF     Unknown  Unknown
python3.7          000055CE517D7A31  _PyCFunction_Fast     Unknown  Unknown
python3.7          000055CE51843EBD  _PyEval_EvalFrame     Unknown  Unknown
python3.7          000055CE51786829  _PyEval_EvalCodeW     Unknown  Unknown
python3.7          000055CE517D7107  _PyFunction_FastC     Unknown  Unknown
python3.7          000055CE5183F4B6  _PyEval_EvalFrame     Unknown  Unknown
python3.7          000055CE51786829  _PyEval_EvalCodeW     Unknown  Unknown
python3.7          000055CE51787714  PyEval_EvalCodeEx     Unknown  Unknown
python3.7          000055CE5178773C  PyEval_EvalCode       Unknown  Unknown
python3.7          000055CE5189EF14  Unknown               Unknown  Unknown
python3.7          000055CE518AA29D  PyRun_StringFlags     Unknown  Unknown
python3.7          000055CE5184EEB4  Unknown               Unknown  Unknown
python3.7          000055CE517D7789  _PyMethodDef_RawF     Unknown  Unknown
python3.7          000055CE517D7A31  _PyCFunction_Fast     Unknown  Unknown
python3.7          000055CE51843795  _PyEval_EvalFrame     Unknown  Unknown
python3.7          000055CE51786829  _PyEval_EvalCodeW     Unknown  Unknown
python3.7          000055CE51787714  PyEval_EvalCodeEx     Unknown  Unknown
python3.7          000055CE5178773C  PyEval_EvalCode       Unknown  Unknown
python3.7          000055CE5189EF14  Unknown               Unknown  Unknown
python3.7          000055CE518A9331  PyRun_FileExFlags     Unknown  Unknown
python3.7          000055CE518A9523  PyRun_SimpleFileE     Unknown  Unknown
python3.7          000055CE518AA655  Unknown               Unknown  Unknown
python3.7          000055CE518AA77C  _Py_UnixMain          Unknown  Unknown
libc-2.27.so       00007F14B6F52BF7  __libc_start_main     Unknown  Unknown
python3.7          000055CE5184EFF0  Unknown               Unknown  Unknown
Aborted (core dumped)
```

**Comment by loriab** [comment] 2021-01-15 22:41
whoa, poltype needs a lot of software! the segfault you posted is not in my power to interpret. do you have access to the file or commands poltype is submitting to psi4? I suspect a bad interaction among software libraries. does `psi4 --test` run ok (that is, no failures)?

**Comment by ahmedo047** [comment] 2021-01-16 00:12
You can see the poltype commands in the `methanol-poltype.log` file:
[methanol_test.zip](https://github.com/psi4/psi4/files/5823465/methanol_test.zip)
And here is `psi4 --test` result:
[output.log](https://github.com/psi4/psi4/files/5823469/output.log)

**Comment by loriab** [comment] 2021-01-16 00:42
Can be fixed with a bigger basis like cc-pvdz. The gradient is fine, so I think the trouble is in predicting the next geom step, so may be of interest to @psi-rking 

```
molecule { 
0 1
 C   -0.167039   -0.712374   -0.022325
 O    0.119573    0.677072    0.056530
 H   -0.453842   -0.989160   -1.036819
 H   -0.997038   -0.962046    0.638968
 H    0.691232   -1.312038    0.284396
 H    0.775814    0.817745    0.757350
}

set optking { 
  frozen_dihedral = ("
    5 1 2 6
    4 1 2 6
    3 1 2 6
  ")
}
#set {
#  geom_maxiter 2
#  g_convergence GAU_LOOSE
#}
#memory 6GB
#set_num_threads(6)
#psi4_io.set_default_path("/home/phy/Desktop/projects/2021/amoeba/test/poltype/scratch/Psi4-methanol")
#for _ in range(1):
#  try:
#    optimize('hf/3-21G')
#    break
#  except OptimizationConvergenceError:
#    break
#  else:
#    try:
#      set opt_coordinates cartesian
#      optimize('hf/3-21G')
#      break
#    except OptimizationConvergenceError:
#      pass
#clean()

optimize("hf/3-21G")  # segfaults
#optimize("hf/cc-pvdz")  # 4 iter
```

**Comment by psi-rking** [comment] 2021-01-16 04:24
I'm not sure what the problem is but this works fine, I'm happy to say :)

set optking {

  frozen_dihedral = ("

    5 1 2 6

    4 1 2 6

    3 1 2 6

  ")

}


#optimize("hf/3-21G")

import optking

set basis 3-21g

optking.optimize_psi4('hf')

**Comment by JonathonMisiewicz** [comment] 2021-06-28 22:57
I don't believe this is an issue in Psi, so closing.

**Closed by JonathonMisiewicz** 2021-06-28 22:57 UTC
