### ISSUE TITLE
eom-cc3 crash on second excitation state

### ISSUE THREAD

**Issue by Konjkov** [psi4/psi4#307] opened 2016-03-09 10:40 UTC
Hi, PSI4 developers.

My input:

```
memory 1000 mb
molecule naphtalene {
0 1
 H                    -3.36584264     1.24097876     0.00000000
 H                    -3.36584264    -1.24097876     0.00000000
 C                    -2.42446866    -0.70593661     0.00000000
 C                    -2.42446866     0.70593661     0.00000000
 H                    -1.23966218    -2.48102176     0.00000000
 C                    -1.24087056    -1.39724699     0.00000000
 H                    -1.23966218     2.48102176     0.00000000
 C                    -1.24087056     1.39724699     0.00000000
 C                     0.00000000    -0.71416200     0.00000000
 C                     0.00000000     0.71416200     0.00000000
 H                     1.23966218    -2.48102176     0.00000000
 C                     1.24087056    -1.39724699     0.00000000
 H                     1.23966218     2.48102176     0.00000000
 C                     1.24087056     1.39724699     0.00000000
 C                     2.42446866    -0.70593661     0.00000000
 C                     2.42446866     0.70593661     0.00000000
 H                     3.36584264     1.24097876     0.00000000
 H                     3.36584264    -1.24097876     0.00000000
}

set {
  basis sto-3g
  scf_type df
  ROOTS_PER_IRREP = [ 0, 0, 0, 0, 0, 0, 1, 1 ]
}

energy('eom-cc3')
```

crash on second excitation state calculation with error:

```
PSIO_ERROR: unit = 128, errval = 18
PSIO_ERROR: 18 (Incorrect block end address)

An error has occurred. Traceback:
<type 'exceptions.RuntimeError'>:.
Fatal Error: PSIO Error
Error occurred in file: /home/vladimir/git/psi4public/src/lib/libpsio/error.cc on line: 123
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::psio_error(unsigned int, unsigned int)
psi::PSIO::read(unsigned int, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::psio_read(unsigned int, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::DPD::file4_mat_irrep_rd(psi::dpdfile4*, int)
:   File "<string>", line 43, in <module>

  File "/usr/local/psi4/share/psi4/python/driver.py", line 586, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)

  File "/usr/local/psi4/share/psi4/python/proc.py", line 2243, in run_eom_cc
    psi4.cceom(ref_wfn)
```

with respect, Vladimir.

**Comment by kannon92** [comment] 2016-03-09 16:18
Not sure if this is the problem, but I don't think you can use DF with CC-EOM.  Could you try scf_type pk or scf_type out_of_core?  

I usually get these PSIO_ERROR when I use DF and later ask for the conventional integrals.

**Comment by amjames** [comment] 2016-03-09 17:40
@Konjkov could you show some of the output above the `PSIO_ERROR`? I am not sure that DF integrals is the culprit here. It would be easier to track down if I could see where in the second exited state it is failing. I ran the input you posted but I don't see the same PSIO_ERROR.

It is strange that the first excited state would be able to run if the integrals were incompatible. Also, the file number 128 is a temporary file used by the CC codes to store things with a short lifetime. If the integrals were the source of the problem I would expect  this kind of error to show up when trying to read some persistent quantity, which would then be used to compute the values that would go into file 128.  

@kannon92 do you have an input that will cause the `PSIO_ERROR` if DF is used? The driver should probably soft-fail with a warning to turn DF off in these cases. It would be very frustrating for a job to run this far just to fail.

**Comment by lothian** [comment] 2016-03-09 17:55
I note that our EOM-CC3 test cases do not include one in which states of
different symmetries are obtained in the same job, so this seems likely to
be a genuine bug (though I could have sworn that we had such calculations
working initially).  The EOM-CC3 algorithm we use computes one state at a
time, but the scratch quantities are likely to be different sizes for
different irreps.

To get around this for now, I suggest simply running the two states in
separate jobs.

-TDC

P.S. I removed the scf_type keyword and reproduced the error, so that's not
the problem.

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by kannon92** [comment] 2016-03-09 18:12
@amjames, I get these errors when I am using my plugins.  I usually don't get it when I am running psi4.

**Comment by dgasmith** [comment] 2016-03-09 18:21
@kannon92 These issues are solved in the driver. Please let us know if you encounter a PSIO 33 or 35 file error in Psi4 proper.

**Comment by amjames** [comment] 2016-11-05 17:08
Closing this since the original  problem seems to be resolved. 

#502 addresses that there are tests missing.

**Closed by amjames** 2016-11-05 17:08 UTC
