### ISSUE TITLE
Davidson completly fails

### ISSUE THREAD

**Issue by wpoely86** [psi4/psi4#175] opened 2015-09-03 17:36 UTC
The input file:

```
memory 1 Gb

molecule NO
{
    1 1
    N
    O 1 R
    units au
}

set {
    guess read

    diag_method rsp

    VECS_WRITE true
    NUM_VECS_WRITE 1

    basis sto-3g
}

NO.R = 2

energy('scf')

NO.R = 50

energy('fci')

set {
    diag_method sem
    GUESS_VECTOR IMPORT
}

energy('fci')
```

I first calculated the RHF solution at 2 Bohr and use it as seed for the solution at 50 Bohr. The first `energy('fci')` uses exact diagonalization and produces the correct energy `-127.1625943265614`. The second call to `energy('fci')` uses Davidson with as start guess the CI vector from the previous calculation. This should immediately convergence yet it finds a ground state energy of `-1527.1801524600446`.  Clearly very far below the actual lowest eigenvalue. Something goes terrible wrong here. 

Any ideas?

It also would be nice if the docs would mention that building the OPDM, etc doesn't work if you use `diag_method rsp`.

**Comment by loriab** [comment] 2015-09-03 19:37
Thanks. The detci module is undergoing C++ modernization and the addition of many new features. Your  issue https://github.com/psi4/psi4public/issues/92 for instance is fixed in the rewrite. Detci's file management is getting re-aligned with Psi4's too. We'll definitely check that your problem isn't present in the new version (the elimination of global (to detci) variables helps for these multiple invokation cases). And if @CDSherrill confirms that the OPDM and `rsp` don't mix, will add to docs.

**Comment by wpoely86** [comment] 2015-09-04 07:42
@loriab the issue is not the multiple invocation. Whatever method I use (davidson, olsen, ...), whatever start guess vector, etc: in ALL cases (except exact diagonalization), detci finds an impossible energy value.

The way the OPDM is currently being build requires information from the davidson algorithm. It can be work around but the current code doesn't allow you to build an opdm with rsp.

**Comment by ryanmrichard** [comment] 2016-01-11 20:31
This does not appear to be fixed with the new CI code.  I now get an energy of -1492.0189996...

**Comment by dgasmith** [comment] 2016-05-05 20:50
Tracked this down: `IMPORT` keyword is very specific to an export CI vector in an old format that is no longer supported, what you wanted was `DFILE` here so that it will read in the old D (or "the" current) CIVector. The `IMPORT` option and all associated content has been removed in an upcoming patch. The `DFILE` and `OPDM` options will now work as RSP will now write out CIVectors. Not entirely what was being read in, but it wasn't a real CIVector.

Now, running this conventionally we still get an energy thats reasonable, but too high by about 5mH. This is apparently caused caused by the `EVANGELISTI` Hamiltonian diagonal approximation for some reason. We usually use this over the exact diagonal to avoid spin contamination, will try to look into this some. For now simply setting `HD_AVG HD_EXACT` will solve the above problems.

**Comment by dgasmith** [comment] 2017-05-13 17:56
`IMPORT` is now deprecated. The issue with the `EVANGELISTI` Hamiltonian diagonal seems to be quite isolated, but I have tagged it to revisit again in the future.

**Closed by dgasmith** 2017-05-13 17:56 UTC
