### ISSUE TITLE
DFJK SCF guess no longer working?

### ISSUE THREAD

**Issue by fevangelista** [psi4/psi4#281] opened 2016-02-25 21:27 UTC
Previously, the following input file would have ran a combination of DFJK and DiskJK calculations.  Now it seems to run DiskJK calculations twice.

```
molecule acetone {
0   1
H   0.000000   2.136732  -0.112445
H   0.000000  -2.136732  -0.112445
H  -0.881334   1.333733  -1.443842
H   0.881334  -1.333733  -1.443842
H  -0.881334  -1.333733  -1.443842
H   0.881334   1.333733  -1.443842
C   0.000000   0.000000   0.000000
C   0.000000   1.287253  -0.795902
C   0.000000  -1.287253  -0.795902
O   0.000000   0.000000   1.227600
units angstrom
}

set globals {
  df_scf_guess     true
  scf_type         PK
  basis            3-21g
  docc             [8, 1, 2, 5]
  guess            GWH
  reference        RHF
  e_convergence    12
}

energy('scf')
```

```
  ==> Primary Basis <==

  Basis Set: 3-21G
    Number of shells: 32
    Number of basis function: 48
    Number of Cartesian functions: 48
    Spherical Harmonics?: false
    Max angular momentum: 1

  ==> Pre-Iterations <==

   -------------------------------------------------------
    Irrep   Nso     Nmo     Nalpha   Nbeta   Ndocc  Nsocc
   -------------------------------------------------------
     A1        21      21       8       8       8       0
     A2         4       4       1       1       1       0
     B1         8       8       2       2       2       0
     B2        15      15       5       5       5       0
   -------------------------------------------------------
    Total      48      48      16      16      16       0
   -------------------------------------------------------

  ==> Integral Setup <==

        Batch   1 pq = [       0,     397] index = [             0,79003]
  ==> DiskJK: Disk-Based J/K Matrices <==

    J tasked:                  Yes
    K tasked:                  Yes
    wK tasked:                  No
    Memory (MB):               715
    Schwarz Cutoff:          1E-12

  Minimum eigenvalue in the overlap matrix is 1.5083126009E-02.
  Using Symmetric Orthogonalization.
  SCF Guess: Generalized Wolfsberg-Helmholtz.

  ==> Iterations <==

                        Total Energy        Delta E     RMS |[F,P]|

   @RHF iter   1:  -187.27391666424671   -1.87274e+02   1.12539e-01
   @RHF iter   2:  -180.35110679174790    6.92281e+00   1.03058e-01 DIIS
   @RHF iter   3:  -189.00974758567247   -8.65864e+00   7.17009e-02 DIIS
   @RHF iter   4:  -190.36715264104453   -1.35741e+00   3.48777e-02 DIIS
   @RHF iter   5:  -190.83292951413978   -4.65777e-01   9.44992e-03 DIIS
   @RHF iter   6:  -190.87826214635624   -4.53326e-02   3.45136e-03 DIIS
   @RHF iter   7:  -190.88536867922011   -7.10653e-03   1.16084e-03 DIIS
   @RHF iter   8:  -190.88604640793187   -6.77729e-04   4.28749e-04 DIIS
   @RHF iter   9:  -190.88629946742424   -2.53059e-04   1.44181e-04 DIIS
   @RHF iter  10:  -190.88631371439720   -1.42470e-05   1.90608e-05 DIIS
   @RHF iter  11:  -190.88631410792334   -3.93526e-07   2.23723e-06 DIIS
   @RHF iter  12:  -190.88631411317886   -5.25552e-09   2.76348e-07 DIIS
   @RHF iter  13:  -190.88631411323206   -5.32054e-11   5.21575e-08 DIIS
   @RHF iter  14:  -190.88631411323365   -1.59162e-12   7.78940e-09 DIIS
   @RHF iter  15:  -190.88631411323342    2.27374e-13   9.99506e-10 DIIS

  DF guess converged.

  ==> Integral Setup <==

        Batch   1 pq = [       0,     397] index = [             0,79003]
  ==> DiskJK: Disk-Based J/K Matrices <==

    J tasked:                  Yes
    K tasked:                  Yes
    wK tasked:                  No
    Memory (MB):               715
    Schwarz Cutoff:          1E-12

   @RHF iter  16:  -190.88631411323331    1.13687e-13   1.51076e-10 DIIS

  ==> Post-Iterations <==
```

**Comment by loriab** [comment] 2016-02-25 21:37
Hmm, I suspect that has to do with the resolution of https://github.com/psi4/psi4private/issues/115 that turned off DF-SCF preiterations for PK. But in this case, you're asking for preiterations, so somehow it's doing them, but not in DF-RHF but in RHF, then telling you "DF guess converged" (which of course makes no sense).

So it's sort of doing what you asked, but what you asked isn't anymore sensible after the previous fix. It doesn't look like it's wasting iterations, but it maybe is wasting integral calculation. How would you like this to behave?

**Comment by jgonthier** [comment] 2016-02-25 22:19
I'm working in the PK code at the moment, so first of all this is not wasting any resources.

@loriab: The problem is when you modified the hf.cc file, you changed the condition for initialization of the DF guess but you forgot to change the convergence condition for this case, line 1969. As a result the code behaves as if it had done DF_SCF_GUESS upon convergence.

We may want the code to print a Warning if df_scf_guess is requested and we forbid it. We could also turn df_scf_guess off by default but let it happen when requested for the non-direct cases. I'd think it is a bit of a waste of resources for PK, but the user may still want it.

**Comment by fevangelista** [comment] 2016-02-26 03:31
@loriab: yes, I forgot that's how we solved psi4/psi4private#115.  Let me point out that I observe the same behavior if turn df_scf_guess on or off.  So my main concern was efficiency, because we seem to recompute the PK integrals twice for both df_scf_guess=off or on.  I think that for consistency we should perhaps warn the user if he/she selects df_scf_guess=off and of course not recompute PK integrals again.  I am not particularly concerned with being able to do DF followed by PK, I just had a test fail in our plugin and I traced it back to the fact that orbitals from DF/PK gave slightly different energies (<1e-10).  Perhaps we could re-enable df_scf_guess=on, but with the new info passing that's not too difficult to reproduce with two scf calculations.

**Comment by jgonthier** [comment] 2016-02-26 16:20
@fevangelista : I think you may not have received a notification from my previous message. I don't think the code is recomputing the PK integrals.

@loriab, @fevangelista : I think the same behaviour is observed with `df_scf_guess on` or `off` is because the driver automatically sets it to `on` ? Is that possible ? In the hf.cc code, everything is supposed to be fine if `df_scf_guess` is `off`.

If nobody is working on that yet I will get on it after lunch and submit a pull request.

**Comment by loriab** [comment] 2016-02-26 18:35
Sorry for messing the fix up, and thanks for diagnosing it, @jgonthier . No, it doesn't look like the driver is touching `df_scf_guess`. read_options defaults it to `on`, but otherwise only `hf.cc` handles that option. Ah, yes, I see what you mean at L1969. If the path to resolve this is clear to you, then yes, please, go ahead and do so, @jgonthier . I'm sort of with @fevangelista that I don't see that we need to facilitate `df_scf_guess` for non-`direct` since it doesn't change the convergence behaviour or reduce quantities to compute. Maybe also change

```c++
    /*- Use DF integrals tech to converge the SCF before switching to a conventional tech -*/
    options.add_bool("DF_SCF_GUESS", true);
```

to

```c++
    /*- Use DF integrals tech to converge the SCF before switching to a conventional tech
    in a |scf__scf_type| ``DIRECT`` calculation -*/
    options.add_bool("DF_SCF_GUESS", true);
```

**Comment by jgonthier** [comment] 2016-02-26 19:28
No problems @loriab, I'll do the fix, you've got enough on your plate :)

@fevangelista : I think we'll keep df_scf_guess turned off for PK, as you mentionned it's quite easy to emulate it directly in the input file.

**Comment by jgonthier** [comment] 2016-02-26 21:04
@fevangelista : I tried to reproduce your problem, and I see it with `df_scf_guess true` but with `df_scf_guess false` the ouptut is the usual one, with no mention of the df guess.

**Comment by jgonthier** [comment] 2016-02-26 22:11
@fevangelista, @loriab : My bad, it *was* recomputing the integrals. I misread the code. Should be fixed with #284.

**Comment by loriab** [comment] 2016-02-26 22:17
Good news, _two_ bugs fixed with this issue then. Thanks, @jgonthier .

**Comment by jgonthier** [comment] 2016-02-26 22:28
I'll close the issue when the PR gets accepted.

**Comment by loriab** [comment] 2016-02-26 22:36
fyi, you can put `fixes psi4/psi4#281` in the commit message of one of the commits in the PR, then the issue will close when the PR gets merged.

**Comment by jgonthier** [comment] 2016-02-27 01:54
Ooooooooooooh I didn't know that. It's awesome. I kind of want something to break again now :D

**Comment by fevangelista** [comment] 2016-02-27 03:52
Thanks for the fix @jgonthier!

**Comment by dgasmith** [comment] 2016-03-01 12:11
@jgonthier Commit 51a5b349d48db40747b9b9e1ac03a81f0b285c74 fix this correct? If so we can go ahead and close.

**Comment by jgonthier** [comment] 2016-03-01 12:21
Indeed. I would have done it myself except I cannnot close issues.

**Closed** 2016-03-01 12:23 UTC
