### ISSUE TITLE
Scratch directory handling broken

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#416] opened 2016-06-20 03:48 UTC
Scratch directory handling seems to be broken in the current trunk.

When I run a calculation without specifying a scratch directory, psi4 uses /tmp as scratch and creates files such as

$ ls /tmp/psi*
/tmp/psi.8361.34  /tmp/psi.8361.35

Now, if I specify a special scratch directory to be used, e.g.

$ cat ~/.psi4rc
psi4_io.set_default_path('/scratch/sslehtola')

the result is not what you'd expect: nothing is in the scratch directory

$ ls /scratch/sslehtola/

However, all sorts of junk appear in the working directory (which is not the same as the scratch directory)

$ ls *psi*
?A??psi.9105.35   G??psi.9105.35  ?H??psi.9105.35  ?N??psi.9105.35  ?<??psi.9105.35  ?+??psi.9105.35  ????psi.9105.35  psi.9105.clean  P?Y?psi.9105.34  P?Y?psi.9105.35

**Comment by susilehtola** [comment] 2016-06-20 03:51
It does work properly if I set

psi4_io.set_default_path('.')

**Comment by dgasmith** [comment] 2016-10-17 23:00
Hmmm, actually this should be fixed on the latest master. Would you mind trying it out again?

**Comment by amjames** [comment] 2016-11-05 17:15
I'm closing this since there has been no activity on the ticket and I can't reproduce the behavior on the current master. 

Please reopen if you are still having trouble.

**Closed by amjames** 2016-11-05 17:15 UTC

**Comment by Saeedreza76** [comment] 2024-07-28 09:32
Hi,
Please, if possible, kindly let me ask a question as follows:

Recently, I lost my Psi4 code and had to again install its newest version 1.9.1 through "Conda-Forge". Moreover, I did build a scratch folder for Psi4 in the Home directory and its path was truly included in ".bashrc"; i.e.
export PATH=/home/saeed/miniconda3/bin:$PATH
export PSI_SCRATCH=/home/saeed/Scratch_PSI4

When a given Psi4 task is ran, the scratch folder is filled and empty alternately. But, after finishing calculations, this folder remains full and there are several files in it that must be deleted manually, while there was no such problem before. Please also let me state that the problem mentioned above only exists for "CBS-extrapolations" calculations while "SAPT" calculations are never encountered such a problem.

Could you please let me know how I can resolve this problem so that this folder, when a task is over, to be emptied automatically as before?

In advance, too many thanks for your highly valuable guidance.

Sincerely,
Saeed
