### ISSUE TITLE
Gaussian FCHK Errors and Inefficiencies

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1272] opened 2018-10-01 15:57 UTC
Reposted from the forum. I can't investigate this myself, due to being banned by Gaussian.

1. The MO and Density blocks are being mislabeled, for all levels of theory as far as I can tell. This prevents 3rd party apps from parsing the files correctly. The labels for the MO orbital energy and coefficients blocks should always be as follows:

Alpha Orbital Energies
Alpha MO Coefficients
Beta Orbital Energies
Beta MO Coefficients

Title case is important.

The Density blocks should be labeled according to the level of theory as follows:

Total SCF Density (this should be the label for both HF and DFT)
Total MP2 Density (don’t prepend ‘DF’ to any methods when using density-fitting)
Total MP3 Density
Total MP4 Density
Total CC Density
Total CI Density

Spin Density should be labeled similarly:

Spin SCF Density (this should be the label for HF, DFT, and CASSCF)
Spin MP2 Density
Spin MP3 Density
Spin MP4 Density
Spin CC Density
Spin CI Density

2. Don’t write the Beta blocks for RHF jobs, as their presence makes 3rd party apps think that the level of theory is UHF, and that in turn leads to unnecessarily expensive calcs

3. If canonical orbitals have been removed from the basis due to S_TOLERANCE, then the “number of independent functions” in the .fchk file should be the resulting number of canonical orbitals. Currently the “number of independent functions” always seems to be equal to the “number of basis functions”, which screws up parsing because the matrices aren’t nbasis x nbasis in this case.

4. This wasn’t happening in v1.1, but in v1.2, writing the .fchk file triggers printing of the MOs to the output file, which bloats the file tremendously. I can’t figure out how to turn this off, but it is undesirable as a default behavior.

**Comment by andysim** [comment] 2018-10-02 12:00
I think the problem is the MOs appearing in the output file in addition to the FCHK file.  Should be an easy one to track down, I hope.

**Comment by susilehtola** [comment] 2018-10-02 12:11
> I think the problem is the MOs appearing in the output file in addition to the FCHK file. Should be an easy one to track down, I hope.

Whoops, that's right..

**Comment by susilehtola** [comment] 2019-01-14 18:20
#1475 now includes fixes to everything else but the spin-restriction; this would be easy to fix as well, I just need a way to check if the calculation is RHF or not.

**Comment by JonathonMisiewicz** [comment] 2019-02-21 13:03
And, reopening. Let me quote the user:
```
Still not working in this latest version.

MP2 and CI jobs both write sections labeled “CC Density”. Instead, MP2 jobs should write “MP2 Density” and CI jobs should write “CI Density”. “CC Density” is for coupled-cluster jobs only.

Also, all post-HF methods are writing the same density to the “SCF Density” section as to their post-HF section. In the case of MP2 and CC jobs, it looks like it’s just the SCF Density. In the case of CI jobs, I think it’s the CI density, but in that case the CI density shouldn’t be written to the “SCF Density” section.
```

The point about the incorrect density being written seems distinct from #1478, as that bug is about the reference wavefunction returning a correlated density, not the correlated wavefunction returning a reference wavefunction.

**Comment by susilehtola** [comment] 2019-02-21 13:57
That’s a cosmetic issue as was discussed here and elsewhere.

The rest isn’t a bug in fchk, but elsewhere in Psi4.

Susi Lehtola
Sent from my phone so excuse my brevity.


On 21 Feb 2019, at 14.03, Jonathon Misiewicz <notifications@github.com<mailto:notifications@github.com>> wrote:


And, reopening. Let me quote the user:

Still not working in this latest version.

MP2 and CI jobs both write sections labeled “CC Density”. Instead, MP2 jobs should write “MP2 Density” and CI jobs should write “CI Density”. “CC Density” is for coupled-cluster jobs only.

Also, all post-HF methods are writing the same density to the “SCF Density” section as to their post-HF section. In the case of MP2 and CC jobs, it looks like it’s just the SCF Density. In the case of CI jobs, I think it’s the CI density, but in that case the CI density shouldn’t be written to the “SCF Density” section.


The point about the incorrect density being written seems distinct from #1478<https://github.com/psi4/psi4/issues/1478>, as that bug is about the reference wavefunction returning a correlated density, not the correlated wavefunction returning a reference wavefunction.

**Comment by JonathonMisiewicz** [comment] 2019-02-23 14:23
It's not clear to me that the label is aesthetic, but I'll assume it is for sake of argument. The mislabeling is still confusing, and it would be good to have the correct label printed. Is there a reason this wasn't done in #1475? The wavefunction's `name` attribute, as I recall, should have the information to specify whether the wavefunction is MP2, CI, CC, etc.

There is discussion elsewhere about the CI density being written to SCF Density (#1478), but I can't find any discussion about the SCF density masquerading as MP2 or CC densities.

**Comment by susilehtola** [comment] 2019-02-24 12:21
Did they build the post-HF density? If not, then of course it'll dump out the SCF density.

**Comment by JonathonMisiewicz** [comment] 2019-02-24 18:55
It would be better for it not to _have_ a correlated density, but it certainly wouldn't output the correlated density if the correlated density is never built.

Did you just want to note that the cause of the correlated density not entering the FCHK is because the correlated density was probably never constructed, or are you making a larger point?

**Comment by dgasmith** [comment] 2019-09-20 13:14
This has gone in circles a bit with different people on the forums and here commenting different ways. This seems more an issues that FCHK is incompletely defined. Is there an answer here that satisfies everyone?

**Comment by susilehtola** [comment] 2019-09-20 17:38
The fchk interface works, the only issues are aesthetic.

However, other parts of Psi4 aren't functioning as they should, i.e. the issue of the reference density.

**Comment by JonathonMisiewicz** [comment] 2019-09-20 20:04
My understanding is that there are two issues:
1. All correlated densities are written to "CC Density". The reference Lori linked (http://wild.life.nctu.edu.tw/~jsyu/compchem/g09/g09ur/f_formchk.htm) says there are separate density sections for MP2, CI, and CC. Susi said it's adequate for the correlated density to be written to one of the three. Forum posters want the densities sent to the "proper" place. I don't know whether the current behavior is adequate for Gaussian or not, but I can easily believe this would confuse some other program that consumes FCHK files. I am not convinced that this is an aesthetic issue and that FCHK is "undefined" in this regard. Again, would it be possible to use the `name` attribute of a wavefunction to figure out the right density title?
2. Sometimes a correlated wavefunction displays as having a "density" which is really the SCF density (http://forum.psicode.org/t/density-labels-in-fchk-files/1445/3) and sometimes the correlated density overwrites the reference density (http://forum.psicode.org/t/problems-with-wavefunction-object-and-fchk-interface/532/13). Issue #1478 mentions this but doesn't go into details. In particular, I'm bothered by the fact that forum users report CC density does not override, but Susi reports that CC density does override. The difference is probably that Susi ran a property computation, but the forum user may have just run an energy computation. This part should be moved to #1478, with a caveat that whoever fixes this should check whether it fixes FCHK problems or not.

**Comment by hokru** [comment] 2020-11-30 08:02
Closing this with #1884 being merged.
New FCHK issues please in a new thread.

**Closed by hokru** 2020-11-30 08:02 UTC
