### ISSUE TITLE
CCSD(T) Fatal Error: Matrix::gemm error: Number of rows and columns do not match

### ISSUE THREAD

**Issue by EthanBullVulpe** [psi4/psi4#2916] opened 2023-04-04 02:01 UTC
I am encountering a problem when doing CCSD(T)/aug-cc-pvtz single point calculations with ghost atoms.
Here is an example input python script:
```
import psi4
geo = """
1 1
         N           -0.319514960239    -0.379524306855     0.559765629138
         C            0.352425639761     0.409233493145    -0.624276970862
         H            0.896212339761     1.229129293145    -0.190264570862
         H           -0.369712060239     1.007481593145    -1.165777070862
         H           -0.938830632741    -1.202223388474     0.119295063837
         H            0.486503344736    -0.886226229665     1.149670412527
         H           -0.828245898402     0.406267805382     1.174683175564
         H            0.972884518932    -0.173541567396    -1.382567158105
        @H           0.158794175371     0.181939104529    -0.283074336970
        @H          -0.134424730413    -0.162256050585     0.233613708927
"""

mol = psi4.geometry(geo)
model = "ccsd(t)/aug-cc-pvtz"

psi4.set_memory('13GB')

psi4.set_num_threads(8)

psi4.core.set_output_file("psi4_ccsdt.outp")

psi4.set_options({
})
e = psi4.energy(model, molecule=mol)

print(e)
```

The SCF converges, but then the calculation crashes, with the following output at the end of the log file (I have attached the full log file to the issue.):
```
        Wfn Parameters:
        --------------------
        Wavefunction         = CCSD_T
        Number of irreps     = 1
        Number of MOs        = 275
        Number of active MOs = 275
        AO-Basis             = NONE
        Semicanonical        = false
        Reference            = RHF
        Print Level          = 1

        IRREP   # MOs   # FZDC  # DOCC  # SOCC  # VIRT  # FZVR
        -----   -----   ------  ------  ------  ------  ------
         A         275      0       9       0       266     0
        Transforming integrals...
        IWL integrals will be deleted.
        (OO|OO)...
        Presorting SO-basis two-electron integrals.
        Sorting File: SO Ints (nn|nn) nbuckets = 1
        Constructing frozen core operators
Row and column block dimensions of A
   (n = 1): 275  
   (n = 1): 275  
Row and column block dimensions of B
   (n = 1): 276  
   (n = 1): 275  
Row and column block dimensions of C
   (n = 1): 275  
   (n = 1): 275  
Asym: 0, Bsym: 0, Csym: 0
Mismatch in index Ha = 0
```

Additionally, the following error message is given:
```
Traceback (most recent call last):
  File "/oasis/tscc/scratch/ebullvul/projects/POPC/timings/debug/psi4test/psi4_ccsdt.py", line 28, in <module>
    e = psi4.energy(model, molecule=mol)
  File "/home/ebullvul/anaconda3/envs/psi4/lib/python3.10/site-packages/psi4/driver/driver.py", line 526, in energy    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/ebullvul/anaconda3/envs/psi4/lib/python3.10/site-packages/psi4/driver/procrouting/proc.py", line 989, in select_ccsd_t_    return func(name, **kwargs)
  File "/home/ebullvul/anaconda3/envs/psi4/lib/python3.10/site-packages/psi4/driver/procrouting/proc.py", line 2898, in run_ccenergy    core.cctransort(ref_wfn)
RuntimeError: 
Fatal Error: Matrix::gemm error: Number of rows and columns do not match.
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1670993662927/work/psi4/src/psi4/libmints/matrix.cc on line: 1389The most recent 5 function calls were:

psi::Matrix::gemm(bool, bool, double, psi::Matrix const*, psi::Matrix const*, double)
psi::Matrix::transform(psi::Matrix const&, psi::Matrix const&, psi::Matrix const&)
```

I am not technically knowledgeable enough to interpret the information about the 'A', 'B', and 'C' matrices in the log file, but it seems like the problem is that their dimensions do not match.

Additionally, I can also report that the calculation works if ANY of the following changes are made to the input:
1) The ghost atoms are removed.
2) The non-augmented basis set is used. (cc-pvtz rather than aug-cc-pvtz)
3) If {'cc_type': 'df'} is passed to psi4.set_options() to do density-fitted coupled cluster.

I installed the stable branch of psi4 through anaconda, I have version "1.7+6ce35a5".

Let me know if there is any more information you need to help solve this issue.

The full log file from the CCSD(T)/aug-cc-pvtz calculation:
[psi4_ccsdt.txt](https://github.com/psi4/psi4/files/11144015/psi4_ccsdt.txt)

**Comment by EthanBullVulpe** [comment] 2023-04-04 02:03
Very sorry, I hit submit before I finished typing the issue. I will update this issue with details about the problem. Thanks.

**Comment by EthanBullVulpe** [comment] 2023-04-04 02:32
I have updated the body of the issue with details about the error message. Thanks in advance!

**Comment by JonathonMisiewicz** [comment] 2023-04-04 11:58
What version of Psi4 are you using? I _suspect_ this was fixed in [a previous PR of mine](https://github.com/psi4/psi4/pull/2857) that hasn't yet been included in any conda releases. I'll confirm when I get to the office.

**Comment by JonathonMisiewicz** [comment] 2023-04-04 14:25
I've confirmed that the computation can proceed past constructing frozen core operators in the latest Psi4. The PR that I linked is probably the reason why.

Do you need assistance in _getting_ the latest Psi4?

**Closed** 2023-04-11 17:09 UTC
