### ISSUE TITLE
Scratch Files Organized Into Process ID Named Folders

### ISSUE THREAD

**Issue by ryanmrichard** [psi4/psi4#81] opened 2015-04-22 19:21 UTC
Currently  our scratch setup is something like:

```
${PSI_SCRATCH}/
     psi.<process_ID>.<File_Number1>
     psi.<process_ID>.<File_Number2>
     psi.<process_ID>.<File_Number3>
```

What I would like is to move to something akin to:

```
${PSI_SCRATCH}/
      <process_ID>/
              psi.<File_Number1>
              psi.<File_Number2>
              psi.<File_Number3>
```

Although, this may seem like a nominal change, it is actually quite significant for MPI based runs.  Currently, if a Psi run creates say 10 files, ${PSI_SCRATCH} contains 10 times ${Number_Of_MPI_Processes} files.  Hence for my 1,000 core job runs, I'm starting to see significant file system lag on account of the number of files in ${PSI_SCRATCH}.  Admittedly the proposed solution would limit us to about 32,000 processes, but I think I can live with that.

In a perfect world, I think it best that scratch files only get written if they are needed.  For my MPI runs, I'm seeing maybe 1 GB of scratch files, per MPI process appearing in the directory.  This means the filesystem lag I'm experiencing is really not necessary as each node has more than enough RAM to hold whatever is being dumped to disk.

Edited: so that the number of MPI processes wasn't a markup command

**Comment by ryanmrichard** [comment] 2015-05-22 14:52
Rethinking this, I think the MPI process ID would be a better labeling system than process ID.  On a Linux box, the max process ID is 32,768 by default (although it can be made higher if you know your machine tolerates integers larger than 16-bit).  Anyways, assuming each MPI process spawns on a separate node, and that the node determines the process ID independently of the other nodes, it's straightforward to show that given n nodes, the probability, p, of two MPI processes having the same process ID  is given by: p=1-exp(-(n)(n-1)/65,536).  Of note, 213 nodes lead to a 50% probability  and 550 nodes lead to a 99% probability.  Hence, if we are going to be massively parallel I think we have to be careful about our usage of process IDs, as they will not be as unique as we are used to thinking they are.

**Comment by ryanmrichard** [comment] 2015-07-07 15:01
In response to @loriab 's call for issues, I'm going to bump this thread.  Moving forward to a massively parallel program something has to be done about the way we handle files.  You have to remember, as Psi4 stands, each MPI process spawns its own files.  For massively parallel runs this is too much.  In my experience most supercomputer have network mounted disk and the ```psi.<pID>.clean``` files alone are hammering it.  I've gotten lucky in that I have access to a supercomputer that has disk on each node, so I've been able to generate data, but long term I don't think we want to limit ourselves to supercomputers with local disk.

I think we need a whole new way of handling files, in particular I'd like to see:
- Less files.  Things should only be written to disk in the event of checkpointing or because the value simply does not fit in memory.
- Virtual files.  The reality is the previous bullet is probably going to be difficult to obtain in practice, which is where support for so-called virtual files comes in.  Basically our file manager would decide whether your file is going to disk or memory and then do the above for you, but as far as your code is concerned you're reading from an actual file.  Thus you get to be agnostic to the details.
- Different numbering/naming scheme.  PID is not a great naming scheme as the possibility of a naming conflict is pretty great (see my last update to this thread).
- The MPI standard also covers disk I/O we should adhere to that...
- Exceptional error messages/detection.  There are a bajillion reasons why file I/O can't occur.
- Compression.  I don't think we compress our files at all, do we?

For the record HDF5 supports virtual files, parallel I/O through MPI, and compression.  Seeing whether it meets our file needs overall is on my todo list, but if someone else wants to take a stab at it in the meantime go for it.

**Comment by ldamore** [comment] 2021-04-09 09:10
I'm wondering why this issue has been closed. I'm having the same problem with massive parallel jobs.

**Comment by hokru** [comment] 2021-04-09 10:47
What kind of massive parallel jobs and problems?

**Comment by JonathonMisiewicz** [comment] 2021-06-27 18:22
Re-closing, since the re-opener failed to provide requested additional details. If somebody wants to reopen this, please provide _specifics_ about what exactly the problem is.

**Closed by JonathonMisiewicz** 2021-06-27 18:22 UTC
