### ISSUE TITLE
Bug: relativistic DF/CD-(FNO)-CCSD

### ISSUE THREAD

**Issue by ludgerpalm** [psi4/psi4#1791] opened 2020-01-30 09:19 UTC
Dear colleagues,

first, please let me again send your whole team a big, big, „Thank you!“ for making this excellent software available to the whole scientific community without barriers like money etc.

Then, it seems I hit a bug:

I ran PSI4 (see attached input and output files for details) on a Linux cluster and reproduced the problem in detail on my MacBook.

Non-relativistic:

CCSD/def2-SVP     OK
CCSD/Jorge-DZP-DKH OK
DF-CCSD/def2-SVP			OK
CD-CCSD/def2-SVP			OK
CD-CCSD/Jorge-DZP-DKH		OK

FNO-CCSD/def2-SVP OK
FNO-CCSD/Jorge-DZP-DKH OK
DF-FNO-CCSD/def2-SVP		OK
CD-FNO-CCSD/def2-SVP		OK
CD-FNO-CCSD/Jorge-DZP-DKH	OK

Relativistic: set relativistic dkh

CCSD/def2-SVP				OK
CCSD/Jorge-DZP-DKH			OK
DF-CCSD/def2-SVP			crashed
CD-CCSD/def2-SVP			crashed
CD-CCSD/Jorge-DZP-DKH		crashed

FNO-CCSD/def2-SVP			OK
FNO-CCSD/Jorge-DZP-DKH 		OK
DF-FNO-CCSD/def2-SVP		crashed
CD-FNO-CCSD/def2-SVP		crashed
CD-FNO-CCSD/Jorge-DZP-DKH	crashed

Hope, you find this helpful.

With best regards

Ludger Palm
ludger.palm@gmx.de

Jorge-DZP-DKH from https://www.basissetexchange.org

[jorge-dzp-dkh.gbs.txt](https://github.com/psi4/psi4/files/4133158/jorge-dzp-dkh.gbs.txt)

[h2.in.txt](https://github.com/psi4/psi4/files/4133171/h2.in.txt)
[h2.out.txt](https://github.com/psi4/psi4/files/4133175/h2.out.txt)

**Comment by hokru** [comment] 2020-01-30 10:12
Thank you for the report. The issue persists with the current development version.
The faulty module is `fnocc`. 
I suspect the error is in the re-computation of the one-electron integrals in the DF-CCSD algorithm (https://github.com/psi4/psi4/blob/master/psi4/src/psi4/fnocc/df_ccsd.cc#L714)

**Comment by JonathonMisiewicz** [comment] 2020-01-30 12:43
That would likely do it. Pinging @fevangelista since this is relevant to #1770.

**Comment by hokru** [comment] 2020-01-30 14:21
I can confirm that the issue are the one-electron integrals.
Also, similar to #1758, because `so_potential()` only knows DKH, DF-FNO-CC calculations do currently not include X2C corrections (and thus do not crash, but would give wrong results).

This would be a fix, I think.
```
H = reference_wavefunction_-> H();
```

Maybe that can be incorporated in PR #1770? Does the PR make it into 1.4?
If not, then I can make a separate hot-fix PR as well. Considering one may otherwise get wrong results with X2C.

**Comment by fevangelista** [comment] 2020-01-30 17:22
I am taking another look at the PR to see if this can be fixed together.

**Comment by fevangelista** [comment] 2020-01-30 17:55
At least for X2C the problems seems to be that FNOCC does not read the relativistic basis. I fixed this problem in #1770 now. I am not sure what's going on with DKH because I am not compiling with that module. It could be the same issue.

**Comment by hokru** [comment] 2020-01-30 18:57
The remaining problem would be that `H` is recalculated manually by directly calling [so_potential](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/mintshelper.cc#L1261) that only knows about DKH and not X2C. 
That means X2C is only included in the SCF energy and not in the Fock matrix in DF/CD-(FNO)-CC.
X2C did not crash the calculation.

Either `H` is taken from the SCF wavefunction object like done elsewhere (e.g in [dfocc](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/dfocc/get_moinfo.cc#L367) or the X2C potential needs to be added somehow.

Direct use of `so_potential` is done here (as far as I could find):
https://github.com/psi4/psi4/blob/master/psi4/src/psi4/fnocc/frozen_natural_orbitals.cc#L1039
https://github.com/psi4/psi4/blob/master/psi4/src/psi4/fnocc/df_ccsd.cc#L714

The other occurrence I found is in the SCF template: https://github.com/psi4/psi4/blob/master/psi4/share/psi4/plugin/scf/scf.cc.template

**Comment by hokru** [comment] 2020-02-04 17:19
Ah! I wasn't aware of all the changes introduced by #1770. My point has been addressed.
The test calculation does not crash and relativistic effects are included where they should be.
I tested DKH and X2C.

This can be closed unless @ludgerpalm has another comment/question to the topic?

**Comment by ludgerpalm** [comment] 2020-02-04 18:30
No, I don't have any other comment. I can hardly follow your conversation ;-)
Thanks for your efforts!

**Comment by loriab** [comment] 2020-02-07 19:09
fixed by #1770

**Closed by loriab** 2020-02-07 19:09 UTC
