### ISSUE TITLE
MP2.5 and MP3 geometry optimizations crash for 2 electron systems

### ISSUE THREAD

**Issue by wardence** [psi4/psi4#893] opened 2018-01-16 16:21 UTC
@bozkaya While running geometry optimizations on a test set of molecules, the MP2.5 and MP3 codes both crash specifically for 2 electron systems without any clear error messages.

Input and output files for H2 and Helium geometry optimizations using MP2.5 or MP3 method, respectively.
[h2_input.txt](https://github.com/psi4/psi4/files/1635881/h2_input.txt)
[h2_output.txt](https://github.com/psi4/psi4/files/1635895/h2_output.txt)
[he_input.txt](https://github.com/psi4/psi4/files/1635897/he_input.txt)
[he_output.txt](https://github.com/psi4/psi4/files/1635899/he_output.txt)

**Comment by bozkaya** [comment] 2018-01-16 17:25
I have no chance to run our input right now. But I can predict that it is due to the misusage of freeze-core true option. Due to that option DFOCC expects some frozen core orbitals but there is not any in reality. If you delete the freeze- core true option, then it will work.

@wardence

**Comment by loriab** [comment] 2018-01-16 17:33
Very true, @bozkaya, and we've done that. We'd really like to be able to run _any_ molecule through a code, though. If the code absolutely can't handle the case, an error is the way to go. But preferably, if the code's contribution is `0.` or unit matrix or anything predictable, I'd really appreciate it if that trivial return could be programmed in. This would greatly help high-throughput calcs or in @wardence's case, multi-stage single calcs.

**Comment by bozkaya** [comment] 2018-01-16 17:38
When coded that part I was not consider the possibility of getting nfrzc zero in case of freeze- core true option. It can be very easily fixed. I am at airport right now :) Tomorrow, I will fix it as a first thing to do. @loriab

**Comment by loriab** [comment] 2018-01-16 17:39
Thanks very much, @bozkaya. Safe travels!

**Comment by bozkaya** [comment] 2018-01-16 17:41
Thank you @loriab

**Comment by bozkaya** [comment] 2018-01-17 08:38
I have fixed the problem and made a PR for it @loriab @wardence

**Comment by loriab** [comment] 2018-01-20 17:13
Thanks very much, @bozkaya! For reference, the commit is ebb63a8a1df9f9f9c270835752f873de7a564b94. @wardence is testing, and she can close this issue after confirmation.

**Comment by loriab** [comment] 2018-04-13 05:41
I believe @wardence confirmed fixed. She can reopen if not.

**Closed by loriab** 2018-04-13 05:41 UTC
