### ISSUE TITLE
Molecule geometry changed but point group symmetry not.

### ISSUE THREAD

**Issue by Konjkov** [psi4/psi4#10] opened 2013-07-07 03:55 UTC
```
# cubane Transition State CСSD(T)/cc-pVDZ geometry optimization

memory 2 Gb

molecule cubane {
 0 1
 H                    -1.460    -1.409    -1.325
 C                    -0.747    -0.790    -0.779
 H                    -1.460    -1.409     1.325
 C                    -0.747    -0.790     0.779
 H                    -1.388     1.387    -1.426
 C                    -0.772     0.772    -0.772
 H                     1.460    -1.460    -1.475
 C                     0.725    -0.725    -1.177
 H                    -1.388     1.387     1.426
 C                    -0.772     0.772     0.772
 H                     1.460    -1.460     1.475
 C                     0.725    -0.725     1.177
 H                     1.409     1.460    -1.325
 C                     0.790     0.747    -0.779
 H                     1.409     1.460     1.325
 C                     0.790     0.747     0.779
}

set {
 basis cc-pVDZ
 opt_type ts
}

set_num_threads(2)

optimize('ccsd(t)')
```

---

Initial molecule has  Molecular point group: cs,    Full point group: Cs
after couple of step geometry optimization atomic coordinates changed to
       Center              X                  Y                   Z
    ------------   -----------------  -----------------  -----------------
           H         -1.473705914299    -1.435393855860    -1.358489164213
           C         -0.797159999078    -0.797004109009    -0.746661382504
           H         -1.476630117570    -1.415339339271     1.362245194949
           C         -0.797740772644    -0.782869624563     0.746875065611
           H         -1.403399626888     1.397804298812    -1.532486210635
           C         -0.816065575433     0.813208518621    -0.796372487595
           H          1.564836624106    -1.553887853367    -0.825942923699
           C          0.782186226366    -0.785194185540    -0.703283447355
           H         -1.398864375817     1.398697058928     1.533459031552
           C         -0.813477696736     0.814494835084     0.795484014989
           H          1.543644549536    -1.569635373854     0.822765427607
           C          0.785442354192    -0.778370034240     0.690456922666
           H          1.425099138027     1.481569438277    -1.355017034180
           C          0.789948918555     0.800919182066    -0.744361460399
           H          1.425889588787     1.478227539320     1.363344118168
           C          0.793832546892     0.798935970506     0.747984335038
but Molecular point group didn't - cs
error issued
ERROR: Symmetry operation 1 did not map atom 7 to another atom:

**Comment by dellelce** [comment] 2015-10-18 17:18
I have a similar issue:

```bash
        --- Internal Coordinate Step in ANG or DEG, aJ/ANG or AJ/DEG ---
         ---------------------------------------------------------------------------
           Coordinate                Previous        Force       Change         New
           ----------                --------       ------       ------       ------
            1 R(1,2)          =      1.257186    -0.000456     0.000097     1.257282
            2 R(2,3)          =      1.320898    -0.000254     0.000757     1.321654
            3 R(3,4)          =      1.225642    -0.003646     0.000429     1.226071
            4 R(4,5)          =      1.320898    -0.000254     0.000695     1.321593
            5 R(5,6)          =      1.257186    -0.000456     0.000044     1.257229
            6 B(1,2,3)        =    178.583593     0.000071     0.528506   179.112099
            7 L(1,2,3)        =    180.000000     0.000000     0.000000   180.000000
            8 B(2,3,4)        =    179.931146     0.000000    -0.988620   178.942526
            9 B(3,4,5)        =    179.931146     0.000000    -0.989069   178.942077
           10 B(4,5,6)        =    178.583593     0.000071     0.528859   179.112452
           11 L(4,5,6)        =    180.000000     0.000000     0.000000   180.000000
           12 L(2,3,4)        =    180.000000     0.000000     0.000000   180.000000
           13 L(3,4,5)        =    180.000000     0.000000     0.000000   180.000000
           14 D(2,3,4,5)      =      0.000000     0.000000    -0.010006    -0.010006
         ---------------------------------------------------------------------------
ERROR: Symmetry operation 1 did not map atom 1 to another atom:
  Molecule:
    Molecular point group: c2v
    Full point group: C2v

    Geometry (in Angstrom), charge = 0, multiplicity = 1:

       Center              X                  Y                   Z               Mass
    ------------   -----------------  -----------------  -----------------  -----------------
           B          3.191343577854     0.013957984675    -0.026816152712    11.009305406000
           N          1.934432141701    -0.005408166154    -0.003207218616    14.003074004780
           C          0.613034927883    -0.005322945846     0.022855273246    12.000000000000
           C         -0.613034934808    -0.005324425017     0.024405755139    12.000000000000
           N         -1.934432149876    -0.005408605424     0.001676100671    14.003074004780
           B         -3.191343562754     0.013958534879    -0.018913757728    11.009305406000

  attempted to find atom at
    -6.030765 0.026377 0.050675
  atom_map() throwing PsiException
Could not symmetrize geometry in OPT::MOLECULE::SYMMETRIZE_GEOM()

  **** Optimization has failed! (in 4 steps) ****
                        --------------------------
                         OPTKING Finished Execution
                        --------------------------
        Cleaning optimization helper files.

*** PSI4 exiting successfully. Buy a developer a beer!
```

not sure what is wrong in my "starter" geometry.

Also the final message ("exiting successfully") after ("Optimization has failed") is a bit disappointing :)

**Comment by dgasmith** [comment] 2016-02-26 15:34
Still fails with the current HEAD (Feb 26, 2015).

```
  attempted to find atom at
    -2.764295 -2.721319 2.493509
  atom_map() throwing PsiException
Could not symmetrize geometry in OPT::MOLECULE::SYMMETRIZE_GEOM()

  **** Optimization has failed! (in 2 steps) ****
```

**Comment by dr-nate** [comment] 2016-03-24 16:00
+1. I have run into similar errors. This is with the simple case of doing a dihedral scan on hydrogen peroxide.

```
ERROR: Symmetry operation 2 did not map atom 1 to another atom:
  Molecule:
    Molecular point group: c2v
    Full point group: C2v

    Geometry (in Angstrom), charge = 0, multiplicity = 1:

       Center              X                  Y                   Z               Mass
    ------------   -----------------  -----------------  -----------------  -----------------
           H          0.021730534334     1.023759611300    -0.835745328589     1.007825032070
           O         -0.026376271469     0.710734621460     0.054491125526    15.994914619560
           O          0.026376271467    -0.710734621234     0.054491125355    15.994914619560
           H         -0.021730534332    -1.023759611527    -0.835745328694     1.007825032070

  attempted to find atom at
    0.041065 -1.934625 -1.579330
  atom_map() throwing PsiException
Could not symmetrize geometry in OPT::MOLECULE::SYMMETRIZE_GEOM()

  **** Optimization has failed! (in 1 steps) ****
```

In my case, some steps fail to optimize while most don't. It's hard to say why some are failing, while other steps are not. It seems that rotation far away from the input molecule conformer are an issue. Though that's not always the case, so...? Here's my input file:

```
molecule HOOH {
0 1
    H   
    O 1 0.90
    O 2 1.40 1 100.0
    H 3 0.90 2 100.0 1 0.0 
}

steps = 35
step_size = 10  
start_angle = -170.0
dihedrals = ["1 2 3 4 {}".format((counter * step_size) + start_angle) for counter in range(0, steps)]
#print(dihedrals)
for dihedral in dihedrals:
    set {
        basis 6-31G*
        scf_type df
        guess sad 
        ints_tolerance 1.0E-8
    }   
    set optking {
        fixed_dihedral = $dihedral
    }   
    optimize('scf')
    SCF_Energy = energy('scf')
```

**Comment by andysim** [comment] 2016-03-25 19:40
This looks like a mismatch in the tolerance used to figure out the point group and the tolerance being used within the optimizer.  For the HOOH case, adding `symmetry c2` to the molecule specification should be a simple workaround.  Also, you can use `SCF_Energy = psi4.get_variable('CURRENT ENERGY')` to avoid running an extra energy calculation.

**Comment by psi-rking** [comment] 2016-03-27 17:27
This erratic behavior is caused by several problems in the optimizer (one of which being the maximum step size getting needlessly scaled down).  However, I believe I've solved all the problems and can now generate a nice, smooth torsional potential curve in C2 symmetry.  I'll push the fix soon.

**Comment by psi-rking** [comment] 2016-03-28 20:55
I've just issued a pull request with some changes to the fixed-coordinate optimizations.  With that code, I am able to get a good dihedral scan for HOOH in C2 with the input below.  (A reminder that, in general, such scans can have erratic jumps since this is not following an IRC, but HOOH is so well-behaved the result is smooth and symmetric anyway.)

```
molecule HOOH {
0 1
 H
 O 1 0.90
 O 2 1.40 1 100.0
 H 3 0.90 2 100.0 1 -175.0
}

set {
  basis 6-31G*
  scf_type df
  guess sad
  ints_tolerance 1.0E-8
}

start_angle = -175.0
steps = 36
step_size = 10

dihedrals = ["1 2 3 4 {}".format((counter * step_size) + start_angle) for counter in range(0, steps)]

SCF_Energies = []

for dihedral in dihedrals:
    set optking { fixed_dihedral = $dihedral }
    optimize('scf')
    SCF_Energies.append( psi4.get_variable('CURRENT ENERGY') )

for i in range(steps):
    print "%10s%20.10f" % (start_angle+i*step_size, SCF_Energies[i])
```
Note that at present the optimizer does not of its own volition head through the discontinuity at 180, even if that path is the shortest to the fixed value.  Thus, I began at -175 and started up.

**Comment by CDSherrill** [comment] 2016-03-28 23:20
Excellent, thanks, Rollin.

Daniel Smith brought up the possibility that we might add a little function
to the driver to automate dihedral scans.  That seems like a good idea.
This input isn't super complicated, but nevertheless I suspect some users
would appreciate automating these loops in a pre-packaged library routine.

**Comment by dgasmith** [comment] 2016-03-29 16:46
The original cubane example still does not work, reopening.

**Comment by dgasmith** [comment] 2016-03-29 19:24
@psi-rking Just FYI this bug occurs with SCF/DFT or MP2 for a cheaper.

For me, the primary concern is the symmetry mapping error is fairly generic. I think a bit clearer error message (if possible) would be sufficient.

**Comment by psi-rking** [comment] 2016-03-30 13:44
I've run this test with both SCF and B3LYP and, although neither
successfully identifies a TS, neither throws an error either.

**Comment by Konjkov** [comment] 2016-03-30 14:10
In this case TS can be found only with casscf(2,2) and mr-ccsd, mr-ccsd(t) and maybe with ccsdt methods, because bond breaking require multireference approach.

**Comment by dgasmith** [comment] 2016-03-30 14:53
@psi-rking Thats very odd, I get a failure at a large number of steps for both SCF and DFT. I guess you can consider that this doesn't identify the TS, but it should still fail with a understandable error message.

**Comment by psi-rking** [comment] 2016-03-30 15:27
OK, I had only run the default 50 steps.

**Comment by dgasmith** [comment] 2016-03-30 15:35
@psi-rking Ah, thats disturbing it appears to be non-deterministic. I find failures between iteration 7 and 35 or the optimization stopping at iteration 50 between separate DF-SCF runs.

**Comment by dgasmith** [comment] 2018-04-13 05:43
The primary issue here has been fixed. It seems that this has migrated to TS optking issue which are better raised in another issue, closing for now.

**Closed by dgasmith** 2018-04-13 05:43 UTC
Labels: confirm-or-deny, optking
