### ISSUE TITLE
Setting SOCC Makes Electrons Disappear

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1370] opened 2018-11-25 18:33 UTC
The following input file:
```
molecule h2o {
H
C 1 r1
O 2 r2 1 a1  
O 2 r2 1 a1 3 180 

r1 = 1.085
r2 = 1.249
a1 = 123.8
}

set reference uhf 
set basis sto-3g

set SOCC [0, 0, 0, 1]

energy('scf')
```
gives an SCF with a single electron. At present, Psi seems to assume `DOCC` is zero if `DOCC` isn't set but `SOCC` is.

**Comment by dgasmith** [comment] 2018-11-30 13:06
This doesn't seem to be an issue per se. Do you have comments on this can be more clear? Without action items we should likely close this.

**Comment by JonathonMisiewicz** [comment] 2018-11-30 14:59
@dgasmith Can you clarify what is unclear? Do you want me to explain why "Psi seems to assume `DOCC` is zero if `DOCC` isn't set but `SOCC` is" is a problem? Detail the expected behavior? Detail how the assumption appears in the code? Something else?

**Comment by loriab** [comment] 2018-11-30 15:06
The problem isn't unclear, but the solution would be complicated, so it probably isn't going to change. For an action item, I was going to suggest adding to the docstring, but looks like the info is [already there](https://github.com/psi4/psi4/blob/master/psi4/src/read_options.cc#L58-L60). You could be more specific about dire consequences (missing electrons) there or add DOCC/SOCC-must-be-paired warnings anywhere else SOCC is discussed in the docs, but I think this is mostly a documentation, not a coding issue. (Actually, it's an options design issue, but too late to change that lightly.)

**Comment by JonathonMisiewicz** [comment] 2018-11-30 15:55
If nothing else, Psi should raise a `ValidationError` during the pre-iteration stage. Seeing that DOCC + SOCC isn't either 0 or the number of electrons shouldn't be difficult to trap.

Do we not have the tech in Psi to let it vary DOCC while fixing SOCC, or more directly, varying the occupation while fixing the spatial symmetry? The point of setting SOCC without DOCC in the original computation was because that seemed to be the only way to select a spatial symmetry without knowing the exact occupation.

**Comment by loriab** [comment] 2018-11-30 16:03
DOCC/SOCC was intended for when you know the exact occupation and want to constrain all else to it. If I understand tales of psi3 days correctly, one essentially always used DOCC/SOCC b/c it was unlikely to ever guess the right occupation. So no, while separate inputs, setting one of DOCC/SOCC signals that those two are the sole source of occupation info, and you can't vary one while setting the other (this is my understanding, not my experience, as I don't play much with open-shell).

The pre-iteration trap you suggest is a good idea. go for it!

**Comment by jturney** [comment] 2018-11-30 16:11
There is certainly a bug in the code where `SOCC` is assumed to be valid when `DOCC` isn't present.  I'd suggest that is modified, too, to be safe: https://github.com/psi4/psi4/blob/0e9f9a53ab260b9e81b95c2355f6bd54b1c47457/psi4/src/psi4/libscf_solver/hf.cc#L178

**Comment by JonathonMisiewicz** [comment] 2018-11-30 16:16
@loriab "Electronic symmetry," yes. Electronic symmetry includes both the spatial symmetry and the spin symmetry. The spin symmetry works just fine. It's the spatial symmetry of the electronic wavefunction that's the trouble. (The distinction is important for my case.)

@jturney Will do. As you can imagine, the symmetry casting/reorientation nightmare will come first.

**Comment by CDSherrill** [comment] 2018-11-30 16:29
Just confirming what @loriab said, the design has always been that DOCC/SOCC are a way for the user to specify manually what the occupations are, and they were always intended to be used together as a pair (although SOCC isn't necessary for closed-shell systems b/c it's just a zero array).  In principle, the entire code should respect DOCC/SOCC directives (this is super useful in some tricky cases).  In practice, I wonder if some developers over the years didn't know what these keywords were, and so didn't allow for them.

________________________________

**Comment by JonathonMisiewicz** [comment] 2018-11-30 17:36
Note to self: `wfn_sym` is apparently a valid option for PSIMRCC. Maybe get the SCF code to accept this as well?

**Closed** 2019-05-02 15:25 UTC
